### ISSUE TITLE
Inspec Exec fails after removal of master branch

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/big-ip-atc-ready#5]
```bash
inspec exec https://github.com/F5SolutionsEngineering/big-ip-atc-ready.git
``` 
fails after the removal of the master branch.  Documentation still also references the master branch.

I've been searching on Google for a way to specify the branch in the inspec exec command and I don't see any option that supports this... can we rename the main branch back to master?

**Comment by mjmenger** [comment]
I reset the default branch to 'master'. I'll research how to change this behavior of inspec.

**Comment by mjmenger** [comment]
FYI the related issue in Inspec was accepted as a defect https://github.com/inspec/inspec/issues/5233
